version: 0.0
os: linux
# https://github.com/andrewpuch/code_deploy_example
files:
  - source: /
    destination: /app
hooks:
  # http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref-hooks.html
  AfterInstall:
    - location: scripts/sql_schema.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
  ValidateService:
    - location: scripts/app_check.sh
      timeout: 300
