---

image: ubuntu:17.04

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y shellcheck python-pip
          - pip install yamllint
          - find . -name "*.sh" | xargs shellcheck
          - >-
            find . . -iregex ".*.ya?ml" |
            xargs yamllint -d '{"extends": "default", "rules": {"line-length": {"level": "warning"}}}'

...
