---

image: ubuntu:17.04

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y shellcheck python-pip
          - pip install yamllint
          - find . -not -path .git -name "*.sh" | xargs shellcheck
          - >-
            find . -not -path .git -iregex ".*.ya?ml" |
            xargs yamllint -d '{
              "extends": "default",
              "rules": {
                "line-length": {
                  "level": "warning"
                }
              }
            }'
  branches:
    master:
      - step:
          image: python:3.6.1
          script:
            - pip install awscli
            - export BUCKET="al-cf-templates-us-east-1"
            - aws s3api head-bucket --bucket "${BUCKET}" || aws s3api create-bucket --bucket "${BUCKET}"
            - aws s3api put-object --bucket "${BUCKET}" --key templates/infrastructure.yaml --body cloudformation/infrastructure.yaml
            - aws s3api put-object --bucket "${BUCKET}" --key templates/infrastructure-networking.yaml --body cloudformation/infrastructure-networking.yaml

...
