AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation ECS MyApp service deploy

Parameters:
  # Resources
  Cluster:
    Type: String
  TaskRole:
    Type: String
  ECSTGMyApp:
    Type: String
  ECSServiceRole:
    Type: String
  CloudwatchLogsGroup:
    Type: String
  # Configurations
  ParamsPrefix:
    Type: String
  DBAddress:
    Type: String
  DockerImage:
    Type: String
  DockerImageTag:
    Type: String

# Resources documentation
# http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
Resources:
  #####################################################################################
  # Start of ECS Service
  #####################################################################################
  MyApp:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 2
      TaskDefinition: !Ref MyAppDefinition
      LoadBalancers:
      - ContainerName: myapp
        ContainerPort: 3000
        TargetGroupArn: !Ref ECSTGMyApp
      Role: !Ref ECSServiceRole
  MyAppDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${AWS::StackName}-myapp"
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
      - Name: myapp
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${DockerImage}:${DockerImageTag}
        Memory: '300'
        Environment:
        - Name: SSM_DB_USERNAME
          Value: !Sub "${ParamsPrefix}.db.username"
        - Name: SSM_DB_PASSWORD
          Value: !Sub "${ParamsPrefix}.db.password"
        - Name: SSM_DB_NAME
          Value: !Sub "${ParamsPrefix}.db.name"
        - Name: DB_CONNECTIONSTRING
          Value: !Ref DBAddress
        PortMappings:
        - ContainerPort: 3000
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref 'CloudwatchLogsGroup'
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: myapp
  #####################################################################################
  # End of ECS
  #####################################################################################
