VPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: '10.250.0.0/16'
    InstanceTenancy: 'default'
    Tags:
      - Key: Name
        Value:
          Fn::Sub: '${AWS::StackName}-VPC'
publicSubnet01:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId:
      Ref: VPC
    CidrBlock: 10.250.0.0/24
    AvailabilityZone:
      Fn::Select:
        - 0
        - Fn::GetAZs: ''
    MapPublicIpOnLaunch: True
    Tags:
      - Key: Name
        Value:
          Fn::Sub: '${AWS::StackName}-PublicSubnet01'
publicSubnet02:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId:
      Ref: VPC
    CidrBlock: 10.250.2.0/24
    AvailabilityZone:
      Fn::Select:
        - 1
        - Fn::GetAZs: ''
    MapPublicIpOnLaunch: True
    Tags:
      - Key: Name
        Value:
          Fn::Sub: '${AWS::StackName}-PublicSubnet02'
privateSubnet01:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId:
      Ref: VPC
    CidrBlock: 10.250.100.0/24
    AvailabilityZone:
      Fn::Select:
        - 0
        - Fn::GetAZs: ''
    Tags:
      - Key: Name
        Value:
          Fn::Sub: '${AWS::StackName}-PrivateSubnet01'
privateSubnet02:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId:
      Ref: VPC
    CidrBlock: 10.250.101.0/24
    AvailabilityZone:
      Fn::Select:
        - 1
        - Fn::GetAZs: ''
    Tags:
      - Key: Name
        Value:
          Fn::Sub: '${AWS::StackName}-PrivateSubnet02'
InternetGateway:
  Type: AWS::EC2::InternetGateway
  DependsOn: [VPC]
  Properties:
    Tags:
      - Key: Name
        Value:
          Fn::Sub: '${AWS::StackName}-InternetGateway'
AttachInternetGateway:
  Type: AWS::EC2::VPCGatewayAttachment
  Properties:
    VpcId:
      Ref: VPC
    InternetGatewayId:
      Ref: InternetGateway
InternetPublicRoutingTable:
  Type: AWS::EC2::RouteTable
  DependsOn: AttachInternetGateway
  Properties:
    VpcId:
      Ref: VPC
    Tags:
      - Key: Name
        Value:
          Fn::Sub: '${AWS::StackName}-InternetRoutingTable'
InternetPublicRoute:
  Type: AWS::EC2::Route
  Properties:
    RouteTableId:
      Ref: InternetPublicRoutingTable
    DestinationCidrBlock: 0.0.0.0/0
    GatewayId:
      Ref: InternetGateway
PublicSubnet01RouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    SubnetId:
      Ref: publicSubnet01
    RouteTableId:
      Ref: InternetPublicRoutingTable
PublicSubnet02RouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    SubnetId:
      Ref: publicSubnet02
    RouteTableId:
      Ref: InternetPublicRoutingTable
